# Generated by Django 3.2.9 on 2021-11-05 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('publishedDate', models.CharField(max_length=10, null=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.URLField(null=True)),
            ],
        ),
    ]
