# Generated by Django 3.2.9 on 2021-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211105_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
